### PR TITLE
Adds indication of whether division outcome supports the policy.

### PR DESCRIPTION
**Pull request by cofiem**
Adds a summary at top of policy page, and extra column in division table.
Addresses first comment on issue #515

### CODE REVIEW

**Comment by cofiem** [comment]
I've only updated tests, not added new tests, as I'm quite confused about how I should go about adding tests (see https://github.com/openaustralia/publicwhip/pull/1159 and https://github.com/openaustralia/publicwhip/issues/1144 ). 

If the maintainers can give me some hints as to how/where they would like tests to be, I can add/change relevant tests.

**Comment by equivalentideas** [comment]
Nice one @cofiem could you add a few screenshots to this to show the before and after at different screen widths for reviewers?

**Comment by cofiem** [comment]
Screenshots of summary at top of page:

Before - large
master-lg

After - large
feature-indicate-division-outcome-support-for-policy-lg

Before - small
master-sm
After - small
feature-indicate-division-outcome-support-for-policy-sm

**Comment by cofiem** [comment]
Screenshots of recent divisions table:

Before - large
master-table-lg

After - large
feature-indicate-division-outcome-support-for-policy-table-lg

Before - small
master-table-sm

After - small
feature-indicate-division-outcome-support-for-policy-table-sm

**Pull request closed without merging**
